### ISSUE TITLE
Remove BOM marker from Python files

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/esss_fix_format#35]
Some users might have their toolset configured to always include a BOM marker.

In our code base we would like to avoid that, as it is redundant for Python (and probably many other text files as well, for example: `.xgui2`).

cc @arthursoprana

**Comment by prusse-martin** [comment]
See #36

**Comment by prusse-martin** [comment]
If we want to add more files to do not include BOM we could hard code that or add that option in the config file (the otion does not exist now nd will need to be added).
